on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
 
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'GovPilot.sln'
 
    runs-on: label-1
 
    steps:
    - uses: actions/checkout@v4
 
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
    - name: Restore dependencies
      run: dotnet restore MyTest12.sln
 
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v2
      with:
       msbuild-architecture: x86
       vswhere-path: 'C:/Program Files (x86)/Microsoft Visual Studio/Installer'
 
    - name: Run Ranorex Tests
      run: msbuild MyTest12.sln
 
    - name: Run the solution
      run: GovPilot/bin/Debug/GovPilot.exe
